#!/bin/bash

power_on() {
    if bluetoothctl show | grep -q "Powered: yes"; then
        echo "Bluetooth: on"
        return 0
    else
        echo "Bluetooth: off"
        return 1
    fi
}

toggle_power() {
    if power_on; then
        bluetoothctl power off
    else
        bluetoothctl power on
    fi
}

toggle_power