#!/bin/bash

# NOTIFICATION 
notification(){
  notify-send -t 5000 "Now Playing:" "$@"
}

# WOFI BEATS MENU NAME
menu(){
  printf "1. Lofi Girl\n"
  printf "2. Lofi Chill\n"
  printf "3. Lofi Zone\n"
  printf "4. Lofi Hip-Hop\n"
  printf "5. Radio Spinner\n"
  printf "6. SmoothChill\n"
  printf "7. Little Soul\n"
  printf "8. Fasetya\n"
  printf "9. Lofi Zone\n"
  printf "10. Lofi\n"
}

# RADIO & PLAYLIST LINKS
main() {
 choice=$(menu | rofi -dmenu -theme ~/.config/rofi/lofi-beats.rasi | cut -d. -f1)

  case $choice in
    1)
      notification "Lofi Girl";
      mpv --shuffle --vid=no "https://www.youtube.com/playlist?list=PLy5uJRaX9m1i8-w2lNNDRndd_RhElX3EQ"
      return
      ;;
    2)
      notification
      mpv "http://stream.zeno.fm/fyn8eh3h5f8uv"
      return
      ;;
    3)
      notification
      mpv "http://stream.zeno.fm/f3wvbbqmdg8uv"
      return
      ;;
    4)
      notification ;
      mpv "http://stream.zeno.fm/0r0xa792kwzuv"
      return
      ;;
    5)
      notification ;
      mpv "https://live.radiospinner.com/lofi-hip-hop-64"
      return
      ;;
    6)
      notification ;
      mpv "https://media-ssl.musicradio.com/SmoothChill"
      return
      ;;
    7)
      notification ;
      mpv --vid=no "https://www.youtube.com/watch?v=NiOxSuEJaTI"
      return
      ;;
    8)
      notification "Lofi-Radio";
      mpv --shuffle --vid=no "https://www.youtube.com/playlist?list=PLy5uJRaX9m1i8-w2lNNDRndd_RhElX3EQ"
      return
      ;;
    9)
      notification ;
      mpv --shuffle --ytdl-raw-options="cookies=/tmp/cookies.txt" --vid=no https://www.youtube.com/watch?v=GaW13eDQO6s
      return
      ;;
    10)
      notification "Lofi-Radio";
      mpv --shuffle --vid=no "https://www.youtube.com/playlist?list=PLy5uJRaX9m1i8-w2lNNDRndd_RhElX3EQ"
      return
      ;;
  esac
}

pkill -f http && notify-send -t 5000 "Lofi Radio Stopped" || main
